package Levyyhtio.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import Levyyhtio.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.03.23 12:10:42 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class LevyyhtioTest {


  // Generated by ComTest BEGIN
  /** testRekisteroi90 */
  @Test
  public void testRekisteroi90() {    // Levyyhtio: 90
    Levyyhtio l = new Levyyhtio(); 
    assertEquals("From: Levyyhtio line: 92", 0, l.getLevyyhtioID()); 
    l.rekisteroi(); 
    assertEquals("From: Levyyhtio line: 94", 1000, l.getLevyyhtioID()); 
  } // Generated by ComTest END
}