package Levyyhtio.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import Levyyhtio.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.03.29 15:23:17 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class LevyyhtioTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi85 */
  @Test
  public void testRekisteroi85() {    // Levyyhtio: 85
    Levyyhtio l = new Levyyhtio(); 
    assertEquals("From: Levyyhtio line: 87", 0, l.getLevyyhtioID()); 
    l.rekisteroi(); 
    assertEquals("From: Levyyhtio line: 89", 1, l.getLevyyhtioID()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse122 */
  @Test
  public void testParse122() {    // Levyyhtio: 122
    Levyyhtio yhtio = new Levyyhtio(); 
    yhtio.parse("   1   |  Creation Records  | 2013"); 
    assertEquals("From: Levyyhtio line: 125", 1, yhtio.getLevyyhtioID()); 
    assertEquals("From: Levyyhtio line: 126", "1|Creation Records|2013", yhtio.toString()); 
    yhtio.rekisteroi(); 
    int n = yhtio.getLevyyhtioID(); 
    yhtio.parse(""+(n+20)); 
    yhtio.rekisteroi(); 
    assertEquals("From: Levyyhtio line: 132", n+20+1, yhtio.getLevyyhtioID()); 
    assertEquals("From: Levyyhtio line: 133", "" + (n+20+1) + "|Creation Records|2013", yhtio.toString()); 
  } // Generated by ComTest END
}