package Kappaleet.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import Kappaleet.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.03.23 11:31:55 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KappaleTest {



  // Generated by ComTest BEGIN
  /** testGetKappaleenNimi47 */
  @Test
  public void testGetKappaleenNimi47() {    // Kappale: 47
    Kappale kappale = new Kappale(); 
    kappale.vastaaSickoMode(); 
    assertEquals("From: Kappale line: 50", "SICKO MODE", kappale.getKappaleenNimi()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRekisteroi128 */
  @Test
  public void testRekisteroi128() {    // Kappale: 128
    Kappale k = new Kappale(); 
    assertEquals("From: Kappale line: 130", 0, k.getKappaleId()); 
    k.rekisteroi(); 
    assertEquals("From: Kappale line: 132", 1, k.getKappaleId()); 
  } // Generated by ComTest END
}