package Kappaleet.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import Kappaleet.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.04.16 11:27:46 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KappaleTest {



  // Generated by ComTest BEGIN
  /** testGetKappaleenNimi48 */
  @Test
  public void testGetKappaleenNimi48() {    // Kappale: 48
    Kappale kappale = new Kappale(); 
    kappale.vastaaSickoMode(); 
    assertEquals("From: Kappale line: 51", "SICKO MODE", kappale.getKappaleenNimi()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRekisteroi241 */
  @Test
  public void testRekisteroi241() {    // Kappale: 241
    Kappale k = new Kappale(); 
    assertEquals("From: Kappale line: 243", 0, k.getKappaleId()); 
    k.rekisteroi(); 
    Kappale k2 = new Kappale(); 
    k2.rekisteroi(); 
    int eka = k.getKappaleId(); 
    int toka = k2.getKappaleId(); 
    assertEquals("From: Kappale line: 249", toka-1, eka); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString275 */
  @Test
  public void testToString275() {    // Kappale: 275
    Kappale kappale = new Kappale(); 
    kappale.parse("   3  |  1   | SICKO MODE"); 
    assertEquals("From: Kappale line: 278", true, kappale.toString().startsWith("3|1|SICKO MODE|"));  // on enemmäkin kuin 3 kenttää, siksi loppu |
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse308 */
  @Test
  public void testParse308() {    // Kappale: 308
    Kappale kappale = new Kappale(); 
    kappale.parse("   3  |  1 | SICKO MODE"); 
    assertEquals("From: Kappale line: 311", 3, kappale.getKappaleId()); 
    assertEquals("From: Kappale line: 312", true, kappale.toString().startsWith("3|1|SICKO MODE|"));  // on enemmäkin kuin 3 kenttää, siksi loppu |
    kappale.rekisteroi(); 
    int n = kappale.getKappaleId(); 
    kappale.parse(""+(n+20));  // Otetaan merkkijonosta vain tunnusnumero
    kappale.rekisteroi();  // ja tarkistetaan että seuraavalla kertaa tulee yhtä isompi
    assertEquals("From: Kappale line: 318", n+20+1, kappale.getKappaleId()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testClone339 
   * @throws CloneNotSupportedException when error
   */
  @Test
  public void testClone339() throws CloneNotSupportedException {    // Kappale: 339
    Kappale kappale = new Kappale(); 
    kappale.parse("   1  |  1  | SICKO MODE"); 
    Kappale kopio = kappale.clone(); 
    assertEquals("From: Kappale line: 344", kappale.toString(), kopio.toString()); 
    kappale.parse("   2  |  Ankka Tupu   | 123"); 
    assertEquals("From: Kappale line: 346", false, kopio.toString().equals(kappale.toString())); 
  } // Generated by ComTest END
}