package Kappaleet.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import Kappaleet.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.04.07 11:15:40 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KappaleetTest {



  // Generated by ComTest BEGIN
  /** 
   * testLisaa48 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa48() throws SailoException {    // Kappaleet: 48
    Kappaleet kt = new Kappaleet(); 
    Kappale k1 = new Kappale(), k2 = new Kappale(); 
    assertEquals("From: Kappaleet line: 52", 0, kt.getLkm()); 
    kt.lisaa(k1); assertEquals("From: Kappaleet line: 53", 1, kt.getLkm()); 
    kt.lisaa(k2); assertEquals("From: Kappaleet line: 54", 2, kt.getLkm()); 
  } // Generated by ComTest END
}