package Kappaleet.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import Kappaleet.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.04.15 09:57:31 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class RekisteriTest {



  // Generated by ComTest BEGIN
  /** 
   * testLisaa86 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa86() throws SailoException {    // Rekisteri: 86
    Rekisteri r = new Rekisteri(); 
    Kappale k1 = new Kappale(); 
    Kappale k2 = new Kappale(); 
    k1.rekisteroi(); k2.rekisteroi(); 
    assertEquals("From: Rekisteri line: 92", 0, r.getKappaleet()); 
    r.lisaa(k1); assertEquals("From: Rekisteri line: 93", 1, r.getKappaleet()); 
    r.lisaa(k2); assertEquals("From: Rekisteri line: 94", 2, r.getKappaleet()); 
  } // Generated by ComTest END
}