package Kappaleet.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import java.util.*;
import Artistit.Artisti;
import Kappaleet.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.03.29 15:07:30 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class RekisteriTest {



  // Generated by ComTest BEGIN
  /** 
   * testLisaa51 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa51() throws SailoException {    // Rekisteri: 51
    Rekisteri r = new Rekisteri(); 
    Kappale k1 = new Kappale(); 
    Kappale k2 = new Kappale(); 
    k1.rekisteroi(); k2.rekisteroi(); 
    assertEquals("From: Rekisteri line: 57", 0, r.getKappaleet()); 
    r.lisaa(k1); assertEquals("From: Rekisteri line: 58", 1, r.getKappaleet()); 
    r.lisaa(k2); assertEquals("From: Rekisteri line: 59", 2, r.getKappaleet()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAnnaArtistit99 */
  @Test
  public void testAnnaArtistit99() {    // Rekisteri: 99
    Rekisteri r = new Rekisteri(); 
    Kappale k1 = new Kappale(), k2 = new Kappale(); 
    k1.rekisteroi(); k2.rekisteroi(); 
    Artisti a1 = new Artisti(); r.lisaa(a1); 
    Artisti a2 = new Artisti(); r.lisaa(a2); 
    List<Artisti> loytyneet; 
    loytyneet = r.annaArtistit(k1); 
    assertEquals("From: Rekisteri line: 110", 2, loytyneet.size()); 
  } // Generated by ComTest END
}