package Artistit.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import Artistit.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.04.14 12:05:25 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class ArtistiTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi95 */
  @Test
  public void testRekisteroi95() {    // Artisti: 95
    Artisti ar = new Artisti(); 
    assertEquals("From: Artisti line: 97", 0, ar.getArtistiID()); 
    ar.rekisteroi(); 
    assertEquals("From: Artisti line: 99", 1, ar.getArtistiID()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse178 */
  @Test
  public void testParse178() {    // Artisti: 178
    Artisti artisti = new Artisti(); 
    artisti.parse("   1   |  10  |   Travis Scott  | 2013"); 
    assertEquals("From: Artisti line: 181", 1, artisti.getArtistiID()); 
    assertEquals("From: Artisti line: 182", "1|10|Travis Scott|2013", artisti.toString()); 
    artisti.rekisteroi(); 
    int n = artisti.getArtistiID(); 
    artisti.parse(""+(n+20)); 
    artisti.rekisteroi(); 
    assertEquals("From: Artisti line: 188", n+20+1, artisti.getArtistiID()); 
    assertEquals("From: Artisti line: 189", "" + (n+20+1) + "|10|Travis Scott|2013", artisti.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testClone232 
   * @throws CloneNotSupportedException when error
   */
  @Test
  public void testClone232() throws CloneNotSupportedException {    // Artisti: 232
    Artisti kappale = new Artisti(); 
    kappale.parse("   1  |  1  | Travis Scott"); 
    Artisti kopio = kappale.clone(); 
    assertEquals("From: Artisti line: 237", kappale.toString(), kopio.toString()); 
    kappale.parse("   2  |  1   | 123"); 
    assertEquals("From: Artisti line: 239", false, kopio.toString().equals(kappale.toString())); 
  } // Generated by ComTest END
}