package Artistit.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import Artistit.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.03.23 11:37:34 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class ArtistiTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi82 */
  @Test
  public void testRekisteroi82() {    // Artisti: 82
    Artisti ar = new Artisti(); 
    assertEquals("From: Artisti line: 84", 0, ar.getArtistiID()); 
    ar.rekisteroi(); 
    assertEquals("From: Artisti line: 86", 99, ar.getArtistiID()); 
  } // Generated by ComTest END
}