package Artistit.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import Artistit.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.03.29 14:55:28 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class ArtistiTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi84 */
  @Test
  public void testRekisteroi84() {    // Artisti: 84
    Artisti ar = new Artisti(); 
    assertEquals("From: Artisti line: 86", 0, ar.getArtistiID()); 
    ar.rekisteroi(); 
    assertEquals("From: Artisti line: 88", 1, ar.getArtistiID()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse155 */
  @Test
  public void testParse155() {    // Artisti: 155
    Artisti artisti = new Artisti(); 
    artisti.parse("   1   |  10  |   Travis Scott  | 2013"); 
    assertEquals("From: Artisti line: 158", 1, artisti.getArtistiID()); 
    assertEquals("From: Artisti line: 159", "1|10|Travis Scott|2013", artisti.toString()); 
    artisti.rekisteroi(); 
    int n = artisti.getArtistiID(); 
    artisti.parse(""+(n+20)); 
    artisti.rekisteroi(); 
    assertEquals("From: Artisti line: 165", n+20+1, artisti.getArtistiID()); 
    assertEquals("From: Artisti line: 166", "" + (n+20+1) + "|10|Travis Scott|2013", artisti.toString()); 
  } // Generated by ComTest END
}