package Artistit.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import Artistit.*;
import java.util.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.03.23 11:50:35 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class ArtistitTest {


  // Generated by ComTest BEGIN
  /** testIterator50 */
  @Test
  public void testIterator50() {    // Artistit: 50
    Artistit ar = new Artistit(); 
    Artisti a1 = new Artisti(10); 
    Artisti a2 = new Artisti(11); 
    ar.lisaa(a1); 
    ar.lisaa(a2); 
    Iterator<Artisti> i2 = ar.iterator(); 
    assertEquals("From: Artistit line: 61", a1, i2.next()); 
    assertEquals("From: Artistit line: 62", a2, i2.next()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAnnaArtistit92 */
  @Test
  public void testAnnaArtistit92() {    // Artistit: 92
    Artistit ar = new Artistit(); 
    Artisti a1 = new Artisti(10); ar.lisaa(a1); 
    Artisti a2 = new Artisti(10); ar.lisaa(a2); 
    List<Artisti> loytyneet; 
    loytyneet = ar.annaArtistit(10); 
    assertEquals("From: Artistit line: 101", 2, loytyneet.size()); 
  } // Generated by ComTest END
}